class GCSystem:
    def __init__(self) -> None: ...
    def collect(self) -> None: ...
    def object_count(self) -> int: ...
    def new_int(self, value: int) -> VMInt: ...
    def new_float(self, value: float) -> VMFloat: ...
    def new_string(self, value: str) -> VMString: ...
    def new_null(self) -> VMNull: ...
    def new_bytes(self, value: bytes) -> VMBytes: ...
    def new_keyval(self, key: object, value: object) -> VMKeyVal: ...
    def new_named(self, name: object, value: object) -> VMNamed: ...
    def new_tuple(self, values: list) -> VMTuple: ...
    def new_wrapper(self, value: object) -> VMWrapper: ...
    def new_range(self, start: int, end: int) -> VMRange: ...

class VMInt:
    def get_value(self) -> int: ...
    def set_value(self, value: int) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class VMFloat:
    def get_value(self) -> float: ...
    def set_value(self, value: float) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class VMString:
    def get_value(self) -> str: ...
    def set_value(self, value: str) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class VMNull:
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class VMBytes:
    def get_value(self) -> bytes: ...
    def set_value(self, value: bytes) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class VMKeyVal:
    def get_key(self) -> object: ...
    def set_key(self, key: object) -> None: ...
    def get_value(self) -> object: ...
    def set_value(self, value: object) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class VMNamed:
    def get_name(self) -> object: ...
    def set_name(self, name: object) -> None: ...
    def get_value(self) -> object: ...
    def set_value(self, value: object) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class VMTuple:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> object: ...
    def to_list(self) -> list: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class VMWrapper:
    def get_value(self) -> object: ...
    def set_value(self, value: object) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class VMRange:
    def get_start(self) -> int: ...
    def get_end(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
